# Generated by Django 5.2.5 on 2025-10-14 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(help_text="Exactamente 5 digitos, agregar 0's (e.g. 00037)", max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_status',
            field=models.CharField(choices=[('activo', 'active'), ('inactivo', 'terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Empleado', 'EMPLOYEE'), ('HR_Admin', 'HR_ADMIN'), ('Master_Admin', 'MASTER_ADMIN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('Fijo (8 Hrs)', 'FIXED_8HRS'), ('Mixto (8 Hrs)', 'MIXED_8HRS'), ('Mixto (12 Hrs)', 'MIXED_12HRS')], default='FIXED_8HRS', max_length=20),
        ),
    ]
